### ISSUE TITLE
Some issue with the Oxford Advanced Learner's Dictionary

### ISSUE THREAD

**Issue by haojie-w** [wayneclub/Apple-Dictionary#2]
After I unzip and move it to the dict directory, it seems it requires install some kind of system extension? I add the dict in the app and the app stop responding after I click the pronounce for any word. I also got prompt from the Privacy & Security settings that I need to enable system extensions... 

Any idea?

**Comment by wayneclub** [comment]
> After I unzip and move it to the dict directory, it seems it requires install some kind of system extension? I add the dict in the app and the app stop responding after I click the pronounce for any word. I also got prompt from the Privacy & Security settings that I need to enable system extensions...
> 
> Any idea?

1. Dictionary App > File > Open Dictionaries Folder
<img width="1512" alt="Screenshot 2024-03-19 at 1 12 38 AM" src="https://github.com/wayneclub/Apple-Dictionary/assets/85578440/7d5b2954-e0bc-4e42-bfb2-d9fe14221370">

2. Move the unzipped folder into the Dictionaries Folder
3. Select custom dictionary in Dictionary > Settings... 
<img width="470" alt="Screenshot 2024-03-19 at 1 13 46 AM" src="https://github.com/wayneclub/Apple-Dictionary/assets/85578440/27897ef8-042d-4c73-b52f-d92ccdb845dc">
